### PR TITLE
Moved all non data-related output to stderr

### PR DESCRIPTION
**Pull request by rakshith-ravi**

### CODE REVIEW

**Review by diptanu — CHANGES_REQUESTED** [review]
Great start! Some more clean up is required during extraction - 

```
diptanuc@firefly:~/Projects/indexify$ ./target/debug/indexify extractor  extract -n diptanu/minilm-l6-extractor  --text "hello world"
2023-12-14T07:43:58.698363Z  INFO indexify::cmd::extractor: using config file: indexify.yaml
2023-12-14T07:43:59.041202Z  INFO indexify: using config file: indexify.yaml
2023-12-14T07:43:59.041217Z  INFO indexify::extractor: no module name provided, looking up indexify.yaml
2023-12-14T07:43:59.041301Z  INFO indexify::extractor: looking up extractor at path: minilm_l6_embedding.py:MiniLML6Extractor
tokenizer_config.json: 100%|##########| 350/350 [00:00<00:00, 714kB/s]
vocab.txt: 100%|##########| 232k/232k [00:00<00:00, 1.94MB/s]
tokenizer.json: 100%|##########| 466k/466k [00:00<00:00, 7.45MB/s]
special_tokens_map.json: 100%|##########| 112/112 [00:00<00:00, 263kB/s]
config.json: 100%|##########| 612/612 [00:00<00:00, 1.36MB/s]
pytorch_model.bin: 100%|##########| 90.9M/90.9M [00:01<00:00, 58.4MB/s]
2023-12-14T07:44:03.903041Z  INFO create_extractor{extractor_path="minilm_l6_embedding.py:MiniLML6Extractor" name="minilm_l6_embedding.py:MiniLML6Extractor"}: indexify::extractor: extractor created: name: minilm_l6_embedding.py:MiniLML6Extractor
, python module: minilm_l6_embedding, class name: MiniLML6Extractor
[
  {
    "content_type": "text/plain",
    "source": [
      104,
      101,
      108,
      108,
      111,
      32,
```

We need to remove all the logs and write only the json data in stdout.

**Comment by rakshith-ravi** [comment]
Okay, got it

**Comment by rakshith-ravi** [comment]
Okay, cleaned up things a bit, and most of it is already fixed. But you won't be able to reproduce it properly because the `indexify` binary that's inside `diptanu/minilm-l6-extractor` is using an older version, which is printing all tracing logs to stdout instead of stderr. If we can update that to use the new binary, then it should be able to spit out only the JSON to stdout.

Was a pain in the butt to debug this, but finally found the issue. I kept wondering why tracing logs are printing out even if I remove tracing from the dependency altogether and remove all parts of it from our code, and then I realised it's not coming from our code. It's coming from the docker image. The `indexify` binary inside the docker image is throwing tracing logs that are coming out to stdout and our code is just printing that to the console.

Simple way to test:
Once you update the docker image with the new binary, run this:
```
docker run --rm diptanu/minilm-l6-extractor extractor extract --text "hello world" 2>/dev/null
```

It should (ideally) only print the JSON. I'll try making my own image from that image and see if I can confirm it from my end as well

**Comment by diptanu** [comment]
Love this! Thank you @rakshith-ravi

**Pull request merged**
