### PR TITLE
add-opensearch support

### PR DESCRIPTION
**Pull request by oleksii-shyman**
- added opensearch vectordb store
  - added initialization of transport with basic authentication

### CODE REVIEW

**Comment by oleksii-shyman** [comment]
FYI -> Development / testing is a problem because of https://forum.opensearch.org/t/keep-getting-forbidden-10-cluster-create-index-blocked/15325

In other words, sometimes index can be created, but sometimes opensearch cluster deployed via docker-compose just falls apart...
opensearch aws is also vulnerable to this issue

**Comment by oleksii-shyman** [comment]
FYI -> was able to run the `getting started` demo with this code. Got the following response that looks good IMO.

{"results":[{"content_id":"b11de1146ff5f9ec","text":"Kevin Durant is the best basketball player in the world.","confidence_score":0.39327487,"metadata":{}},{"content_id":"a64c6ddc9683f031","text":"Indexify is a retrieval service for LLM agents!","confidence_score":0.3305549,"metadata":{}},{"content_id":"5e55fda07f7be40b","text":"Indexify is amazing!","confidence_score":0.32298186,"metadata":{}}]}

There is a problem. It took around 3 minutes on my desktop to index 3 documents -_-
I am not sure that this is acceptable.

**Review by diptanu — APPROVED** [review]
LGTM

**Comment by diptanu** [comment]
Tests will pass if you rebase master

**Pull request merged**
